config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  resources :users
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title,       presence: true
  validates :partner,     presence: true
  validates :explanation, presence: true
  validates :price,       presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :destroy, :update]
  before_action :move_to_index, except: [:index, :show]

  def index
    @items = Item.includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  def destroy
    @item.destroy
  end

  def edit
  end

  def show
  end

  def update
    @item.update(item_params)
  end


  private
  def item_params
    params.require(:item).permit(:title, :partner, :explanation, :price).merge(user_id: current_user.id)
    
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in? 
      @items = current_user.items
    else
      redirect_to root_path
    end
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
保存完了！！
<a class="btn" href="/">投稿一覧へ戻る</a>

app/views/items/destroy.html.erb
経費の削除が完了しました
<a href="/">投稿一覧へ戻る</a>

app/views/items/edit.html.erb
<h3>経費の編集</h3>
  <%= form_with(model: @item, local: true) do |form| %>
    <%= "登録ユーザーid：#{@item.user.id}" %><br>
    <%= "登録ユーザー名：#{@item.user.nickname}" %><br>
    <%= form.text_field :title, placeholder: "XXXに関する費用" %><br>
    <%= form.text_field :partner, placeholder: "●●株式会社" %><br>
    <%= form.text_area :explanation, placeholder: "XXXXXXXXXXXXX", rows: "5" %><br>
    <%= form.text_field :price, placeholder: "XXXXXXXXXXXXX" %>円<br>
    <%= form.submit "保存" %><br>
  <% end %>

app/views/items/index.html.erb
<h3>経費の一覧</h3>
<% if user_signed_in?%> 
  <%= "#{current_user.nickname}さん、こんにちは"%><br>
  <%= link_to "マイページへ", user_path(current_user.id), method: :get%><br>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete%><br>
<% else %>
  <%= link_to "新規ユーザー登録", new_user_registration_path, method: :get%><br>
  <%= link_to "ログイン", new_user_session_path, method: :get%><br>
<% end %>
---<br>
<%=link_to '新しい経費の登録', new_item_path %><br>
---<br>
<% @items.each do |item| %>
  <li><%= "タイトル：#{item.title}" %></li>
  <li><%= "相手先：#{item.partner}" %></li>
  <li><%= "説明：#{item.explanation}" %></li>
  <li><%= "価格：#{item.price}円" %></li>
  <li><%= "ユーザーid：#{item.user.id}" %></li>
  <li><%= "ユーザーname：#{item.user.nickname}" %></li>
  <% if user_signed_in? && current_user.id == item.user.id %>
  <li><%= link_to '編集', edit_item_path(item.id), method: :get %></li>
  <li><%= link_to '削除', item_path(item.id), method: :delete %></li>
  <% else %>
  <li><%= link_to '詳細表示', item_path(item.id), method: :get %></li>
  <% end %>
  <span>-----------------</span>
<% end %>

app/views/items/new.html.erb
<h3>経費の登録</h3>
  <%= form_with(model: @item, local: true) do |form| %>
    <%= form.text_field :title, placeholder: "XXXに関する費用" %>
    <%= form.text_field :partner, placeholder: "●●株式会社" %>
    <%= form.text_area :explanation, placeholder: "XXXXXXXXXXXXX", rows: "5" %>
    <%= form.text_field :price, placeholder: "XXXXXXXXXXXXX" %>円
    <%= form.submit "保存" %>
  <% end %>

app/views/items/show.html.erb
----------------------------------------------<br>
  <li><%= "タイトル：#{@item.title}" %></li>
  <li><%= "相手先：#{@item.partner}" %></li>
  <li><%= "説明：#{@item.explanation}" %></li>
  <li><%= "価格：#{@item.price}円" %></li>
----------------------------------------------<br>
  <a href="/">投稿一覧へ戻る</a><br>
  <% if user_signed_in? && current_user.id == @item.user.id %>
  <%= link_to 'この経費を編集する', edit_item_path(@item.id), method: :get %><br>
  <%= link_to 'この経費を削除する', item_path(@item.id), method: :delete %><br>
  <% end %>

app/views/items/update.html.erb
経費の更新が完了しました<br>
<a href="/">トップページへ</a><br>
<%= link_to "マイページへ戻る", user_path(current_user.id), method: :get%><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SquimaKeiri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<p><%= current_user.nickname %>さんの投稿一覧</p>
  <% @items.each do |item| %>
      -----------------------------------<br>
      <li><%= "タイトル：#{item.title}" %></li>
      <li><%= "相手先：#{item.partner}" %></li>
      <li><%= "説明：#{item.explanation}" %></li>
      <li><%= "価格：#{item.price}円" %></li>
      <li><%= "ユーザーid：#{item.user.id}" %></li>
      <li><%= "ユーザーname：#{item.user.nickname}" %></li>
      <li><%= link_to 'この経費を編集する', edit_item_path(item.id), method: :get %></li>
      <li><%= link_to 'この経費を削除する', item_path(item.id), method: :delete %></li>

  <% end %>